TARGET_SPECIFIC_HEADER_PATH := device/semc/msm7x27-common/include

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/semc/msm7x27-common/bluedroid

## Camera
USE_CAMERA_STUB := true
BOARD_USES_ECLAIR_LIBCAMERA := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
BUILD_CAMERAHAL := true
TARGET_DISABLE_ARM_PIE := true
BOARD_CPU_COLOR_CONVERT := true
BOARD_USES_LEGACY_CAMERA := true

# CPU
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi
TARGET_CPU_ABI2 := armeabi-v6l
TARGET_CPU_VARIANT := arm11
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_BOARD_PLATFORM := msm7x27
TARGET_ARCH_LOWMEM := true
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := msm7x27
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000

# Bluetooth
BOARD_HAVE_BLUETOOTH := true

## Lights
TARGET_PROVIDES_LIBLIGHTS := true

## RIL
BOARD_USES_LEGACY_RIL :=true

## Usb
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
BOARD_UMS_LUNFILE := "/sys/devices/platform/msm_hsusb/gadget/lun0/file"
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/msm_hsusb/gadget/lun0/file"

## Custom CFLAGS
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DTARGET_MSM7x27
COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_COMPAT -DQCOM_NO_SECURE_PLAYBACK
#COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_PIXEL_FORMAT_YV12 -DMISSING_GRALLOC_BUFFERS -DMISSING_EGL_EXTERNAL_IMAGE
COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT
COMMON_GLOBAL_CFLAGS += -DECLAIR_LIBCAMERA
COMMON_GLOBAL_CFLAGS += -DQCOM_LEGACY_OMX
COMMON_GLOBAL_CFLAGS += -DANCIENT_GL

#COMMON_GLOBAL_CFLAGS += -DTARGET_MSM7x27
#COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
#COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60
#COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_COMPAT

#COMMON_GLOBAL_CFLAGS += -DICS_AUDIO_BLOB
#COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK
#COMMON_GLOBAL_CFLAGS += -DCPU_COLOR_CONVERT
#COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_EXTERNAL_IMAGE -DMISSING_GRALLOC_BUFFERS
#COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_PIXEL_FORMAT_YV12

#COMMON_GLOBAL_CFLAGS += -DBOARD_GL_OES_EGL_IMG_EXTERNAL_HACK
#COMMON_GLOBAL_CFLAGS += -DFORCE_CPU_UPLOAD
#COMMON_GLOBAL_CFLAGS += -DEGL_TRACE
#COMMON_GLOBAL_CFLAGS += -D_INTERNAL_BINDER_PARCEL_

### Webkit and browser
#PRODUCT_PREBUILT_WEBVIEWCHROMIUM := yes
TARGET_FORCE_CPU_UPLOAD := true
JS_ENGINE := v8
HTTP := chrome
ENABLE_JSC_JIT := true

## HW ACCEL
BOARD_EGL_CFG := device/semc/msm7x27-common/prebuilt/egl.cfg
BOARD_USES_QCOM_HARDWARE := true
TARGET_QCOM_DISPLAY_VARIANT := legacy
BOARD_EGL_WORKAROUND_BUG_10194508 := true
USE_OPENGL_RENDERER := true
TARGET_NO_HW_VSYNC := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
BOARD_USE_MHEAP_SCREENSHOT := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BUILD_WITH_FULL_STAGEFRIGHT=true
BOARD_EGL_NEEDS_LEGACY_FB := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
TARGET_NO_SEPARATE_RECOVERY := true

# QCOM enhanced A/V
TARGET_QCOM_MEDIA_VARIANT := legacy
TARGET_ENABLE_AV_ENHANCEMENTS := true

## Kernel
BOARD_KERNEL_CMDLINE := console=null
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 0x00000800
BOARD_SDCARD_INTERNAL_DEVICE := /dev/block/mmcblk0p1
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
BOARD_CUSTOM_BOOTIMG_MK := device/semc/msm7x27-common/custombootimg.mk
#TARGET_KERNEL_SOURCE := kernel/semc/msm7x30
#TARGET_NO_KERNEL := true

## Audio
TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_GENERIC_AUDIO := false
#BOARD_COMBO_DEVICE_SUPPORTED := true
#BOARD_USES_AUDIO_LEGACY := false

## Wifi & hotspot
BOARD_WPA_SUPPLICANT_DRIVER      := NL80211
WPA_SUPPLICANT_VERSION           := VER_0_8_X
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_wl12xx
BOARD_HOSTAPD_DRIVER             := NL80211
BOARD_HOSTAPD_PRIVATE_LIB        := lib_driver_cmd_wl12xx
BOARD_WLAN_DEVICE                := wl12xx_mac80211
BOARD_SOFTAP_DEVICE              := wl12xx_mac80211
USES_TI_MAC80211 := true

# Required for newer wpa_supplicant_8_ti versions to fix tethering
BOARD_WIFI_SKIP_CAPABILITIES := true

COMMON_GLOBAL_CFLAGS += -DUSES_TI_MAC80211

# Bluetooth
BOARD_WPAN_DEVICE := true
BOARD_HAVE_BLUETOOTH_TI := true

# FM Radio
TARGET_PROVIDES_TI_FM_SERVICE := true
#BOARD_HAVE_QCOM_FM := true
#COMMON_GLOBAL_CFLAGS += -DQCOM_FM_ENABLED -DHAVE_SEMC_FM_RADIO

## Odex
WITH_DEXPREOPT := false

## Bootanimation
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

## Recovery
TARGET_RECOVERY_PRE_COMMAND := "touch /cache/recovery/boot;sync;"
#BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/semc/msm7x27-common/recovery/recovery_keys.c

## A custom ota package maker for a device without a boot partition
TARGET_RELEASETOOL_OTA_FROM_TARGET_SCRIPT := device/semc/msm7x27-common/releasetools/semc_ota_from_target_files

## Prelinks
PRODUCT_SPECIFIC_DEFINES += TARGET_PRELINKER_MAP=$(TOP)/device/semc/msm7x27-common/prelink-linux-arm-msm7x27.map

## Misc
#BOARD_USE_LEGACY_TOUCHSCREEN := true

